source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.10'

target 'SwiftAlamofireCodeGenerator' do
  #pod 'Alamofire', '~> 1.1'
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'xcode-6.3'
end
